Added Siri Intent
tr1ckyf0x/wakeonlan-ios pull request #31
Opened 2022-09-07 09:45 UTC by tr1ckyf0x

Issue #29

2022-09-07 19:56 UTC, Dm94st requested changes

2022-09-07 19:56 UTC, Dm94st commented on Intent/WOLIntentHandler.swift
> +                print(availableHostnames)
давай уберем

2022-09-07 19:56 UTC, Dm94st commented on Intent/WOLIntentHandler.swift
> +extension WOLIntentHandler {
```suggestion
private extension WOLIntentHandler {
```

2022-09-07 19:56 UTC, Dm94st commented on Wake On Lan/Modules/CoreDataService/sourcery.yml
> +configurations:
я бы все-таки разделил это ПР-ы. в первом добавление мокабл, в другом siri.

2022-09-07 19:56 UTC, Dm94st commented on Wake On Lan/Modules/CoreDataService/Sources/Migrations/CoreDataMigrationController.swift
> +public final class CoreDataMigrationController {
а поч контроллер? так то по идее это воркер не более

2022-09-07 19:56 UTC, Dm94st commented on Wake On Lan/Modules/CoreDataService/Sources/Migrations/CoreDataMigrationController.swift
> +        (migration as? CoreDataMigrationInternal)?
тут без кастования никак?

2022-09-07 19:56 UTC, Dm94st commented on Wake On Lan/Modules/CoreDataService/Sources/CoreDataPersistentService.swift
> +    var hasLoadedStores = false
точно этот флаг нужен? без него никак?

2022-09-07 19:56 UTC, Dm94st commented on Wake On Lan/Modules/CoreDataService/Sources/Migrations/CoreDataAppToSharedGroupMigration.swift
> +extension CoreDataAppToSharedGroupMigration {
тоже можно приватным сразу сделать

2022-09-08 04:37 UTC, tr1ckyf0x commented on Wake On Lan/Modules/CoreDataService/Sources/Migrations/CoreDataMigrationController.swift
> +        (migration as? CoreDataMigrationInternal)?
там публично должен торчать только публичный протокол, я только такой вариант придумал

2022-09-08 04:38 UTC, tr1ckyf0x commented on Wake On Lan/Modules/CoreDataService/Sources/CoreDataPersistentService.swift
> +    var hasLoadedStores = false
я думаю перенести его в IntentHandler

2022-09-08 09:18 UTC, Dm94st commented on Wake On Lan/Modules/CoreDataService/Sources/CoreDataPersistentService.swift
> +    private(set) lazy var managedObjectModel: NSManagedObjectModel = {
а зачем ?

2022-09-08 09:43 UTC, tr1ckyf0x commented on Wake On Lan/Modules/CoreDataService/Sources/CoreDataPersistentService.swift
> +    private(set) lazy var managedObjectModel: NSManagedObjectModel = {
Чтобы ограничить права

2022-09-08 21:12 UTC, Dm94st commented on Wake On Lan/Modules/CoreDataService/Sources/Migrations/CoreDataAppToSharedGroupMigration.swift
> +            if let deletionError = deletionError {
энивей, я бы не оставлял висящих переменных

2022-09-08 21:12 UTC, Dm94st commented on Wake On Lan/Modules/CoreDataService/Sources/Migrations/CoreDataAppToSharedGroupMigration.swift
> +    public convenience init(
ИМХО - в нем смысла нету особо, можно же файл менеджер по дефолту и так прокинуть в основном ините

2022-09-08 21:12 UTC, Dm94st commented on Wake On Lan/Modules/CoreDataService/Sources/Migrations/CoreDataAppToSharedGroupMigration.swift
> +            // Migration not required
тут надо либо лог добавить либо бросать исключение

2022-09-08 21:12 UTC, Dm94st commented on Wake On Lan/Modules/CoreDataService/Sources/FileManagerProtocol.swift
> +protocol FileManagerProtocol {
у нас есть модуль `SharedProtocols`, давай туда. и давай еще добавим quick help для всех методов, ибо это публичный протокол

2022-09-08 21:12 UTC, Dm94st commented on Wake On Lan/Modules/CoreDataService/Sources/Migrations/CoreDataAppToSharedGroupMigration.swift
> +    private func files(containing substring: String, at directoryURL: URL) throws -> [URL] {
```suggestion
    private func fetchFiles(containing substring: String, at directoryURL: URL) throws -> [URL] {
```

2022-09-08 21:12 UTC, Dm94st commented on Wake On Lan/Modules/CoreDataService/Sources/Migrations/CoreDataAppToSharedGroupMigration.swift
> +    private func oldDatabaseFileURLs() throws-> [URL] {
```suggestion
    private func fetchOldDatabaseFileURLs() throws-> [URL] {
```

2022-09-08 21:12 UTC, Dm94st commented on Wake On Lan/Modules/CoreDataService/Sources/Migrations/CoreDataAppToSharedGroupMigration.swift
> +    private func oldDatabaseURL() throws -> URL? {
```suggestion
    private func fetchOldDatabaseURL() throws -> URL? {
```

2022-09-08 21:12 UTC, Dm94st commented on Wake On Lan/Modules/CoreDataService/Sources/CoreDataConstants.swift
> +    static let sharedAppGroupIdentifier = "group.com.tr1ckyf0x.wake-on-lan.shared"
а мы не можем его выдернуть из ресурсов или откуда еще?

2022-09-08 21:12 UTC, Dm94st commented on Wake On Lan/Modules/CoreDataService/Sources/CoreDataConstants.swift
> +    static let iCloudContainerIdentifier = "iCloud.com.tr1ckyf0x.wake-on-lan"
и этот

2022-09-08 21:12 UTC, Dm94st commented on Wake On Lan/AppDelegate.swift
> +            try await coreDataMigrationQueue
получется, что будем висеть, пока все миграции не выполнятся? (это не претензия, просто вопрос)

2022-09-08 21:12 UTC, Dm94st commented on IntentSharedSources/ru.lproj/Intents.strings
> +"AwEh3n" = "Включить ${hostname}";
а почему строки такие? типа `AwEh3n` и тд

2022-09-09 04:08 UTC, tr1ckyf0x commented on Wake On Lan/Modules/CoreDataService/Sources/CoreDataPersistentService.swift
> +    private(set) lazy var managedObjectModel: NSManagedObjectModel = {
А, вижу, да. Мне нужна была модель в классе миграции, теперь уже не актуально

2022-09-09 04:12 UTC, tr1ckyf0x commented on Wake On Lan/Modules/CoreDataService/Sources/Migrations/CoreDataMigrationQueue.swift
> +public final class CoreDataMigrationQueue {
Ну вот пока что может быть и не нужно

2022-09-09 04:14 UTC, tr1ckyf0x commented on Wake On Lan/Modules/CoreDataService/Sources/Migrations/CoreDataAppToSharedGroupMigration.swift
> +            if let deletionError = deletionError {
throw вызывается в non-throwing замыкании, потому приходится так обрабатывать

2022-09-09 04:15 UTC, tr1ckyf0x commented on Wake On Lan/Modules/CoreDataService/Sources/Migrations/CoreDataAppToSharedGroupMigration.swift
> +    public convenience init(
Основной init я не могу сделать public, потому что FileManagerProtocol internal

2022-09-09 04:16 UTC, tr1ckyf0x commented on Wake On Lan/Modules/CoreDataService/Sources/FileManagerProtocol.swift
> +protocol FileManagerProtocol {
Это как раз не публичный протокол

2022-09-09 04:17 UTC, tr1ckyf0x commented on Wake On Lan/AppDelegate.swift
> +            try await coreDataMigrationQueue
висеть будеть внутри Task

2022-09-09 04:18 UTC, tr1ckyf0x commented on IntentSharedSources/ru.lproj/Intents.strings
> +"AwEh3n" = "Включить ${hostname}";
Они сгенерированы Xcode из .intentsdefinition

2022-09-09 04:30 UTC, tr1ckyf0x commented on IntentSharedSources/ru.lproj/Intents.strings
> +"AwEh3n" = "Включить ${hostname}";
Это как сториборды когда локализируешь

2022-09-09 04:32 UTC, tr1ckyf0x commented on Wake On Lan/Modules/CoreDataService/Sources/CoreDataConstants.swift
> +    static let sharedAppGroupIdentifier = "group.com.tr1ckyf0x.wake-on-lan.shared"
Только если пропишем в Info.plist

2022-09-09 04:40 UTC, tr1ckyf0x commented on Wake On Lan/Modules/CoreDataService/Sources/Migrations/CoreDataAppToSharedGroupMigration.swift
> +            // Migration not required
Я добавил TODO на добавление логов. Нужно сначала логгер написать

2022-09-11 13:59 UTC, Dm94st commented on Intent/IntentHandler.swift
> +    private static var wakeOnLanService: WakeOnLanServiceProtocol = WakeOnLanService()
```suggestion
    private static let wakeOnLanService: WakeOnLanServiceProtocol = WakeOnLanService()
```

2022-09-11 14:09 UTC, tr1ckyf0x commented on Wake On Lan/Modules/CoreDataService/Sources/CoreDataServiceProtocol.swift
> +    public func createHostContainer() async {
Убрать completion и удалить

2022-09-11 16:14 UTC, Dm94st commented on Wake On Lan/Modules/CoreDataService/Sources/Migrations/CoreDataAppToSharedGroupMigration.swift
> +                error: nil,
давай обработаем эту ошибку, этого будет достаточно ссылаясь на доку.

2022-09-11 16:15 UTC, Dm94st commented on Wake On Lan/Modules/CoreDataService/Sources/Migrations/CoreDataAppToSharedGroupMigration.swift
> +    private func removeOldDatabaseFiles() throws {
операция под капотом может быть долгой, так что давай сделаем `async`. 
Workaround: https://stackoverflow.com/questions/69257947/filemanager-removeitemat-takes-long-how-do-i-know-when-its-done

2022-09-11 19:44 UTC, merged