Added In-App donations
tr1ckyf0x/wakeonlan-ios pull request #54
Opened 2023-04-30 10:52 UTC by tr1ckyf0x

2023-05-01 11:57 UTC, Dm94st requested changes

2023-05-01 11:57 UTC, Dm94st commented on Wake On Lan/Modules/IAPManager/Sources/IAPManager/IAPManager.swift
> +public protocol ManagesIAP {
на все паблик-сущности нужны quick help

2023-05-01 11:57 UTC, Dm94st commented on Wake On Lan/Modules/IAPManager/Sources/IAPManager/IAPManager.swift
> +    func purchase(product: Product) async throws
```suggestion
    func fetchPurchase(by product: Product) async throws
```

2023-05-01 11:57 UTC, Dm94st commented on Wake On Lan/Modules/IAPManager/Sources/IAPManager/IAPManager.swift
> +        Set(ProductIdentifier.allCases.map(\.rawValue))
что это?

2023-05-01 11:57 UTC, Dm94st commented on Wake On Lan/Modules/IAPManager/Sources/IAPManager/IAPManager.swift
> +    func purchase(product: Product) async throws
вообще не ясно из нейминга что это. get/fetch/make/whatever?

2023-05-01 11:57 UTC, Dm94st commented on Wake On Lan/Modules/IAPManager/Sources/IAPManager/IAPManager.swift
> +        formatter.locale = product.priceLocale
вот тут не будет никаких проблем?

2023-05-01 11:57 UTC, Dm94st commented on Wake On Lan/Modules/IAPManager/Sources/IAPManager/Payment.swift
> +final class Payment: NSObject {
это что за штука? надо бы закрыть протоколом и накинуть квик хелп

2023-05-01 11:57 UTC, Dm94st commented on Wake On Lan/Modules/IAPManager/Sources/IAPManager/Payment.swift
> +            self.continuation = continuation
почему мы ее сохранять должны? зачем? нельзя просто из коллбека забрать?

2023-05-01 11:57 UTC, Dm94st commented on Wake On Lan/Modules/IAPManager/Sources/IAPManager/Payment.swift
> +    public func paymentQueue(
класс интернал а метод паблик?

2023-05-01 11:57 UTC, Dm94st commented on Wake On Lan/Modules/IAPManager/Sources/IAPManager/Payment.swift
> +    public func paymentQueue(
класс интернал а метод паблик?

2023-05-01 11:57 UTC, Dm94st commented on Wake On Lan/Modules/IAPManager/Sources/IAPManager/Payment.swift
> +        case .deferred:
можно объединить в один кейс

2023-05-01 11:57 UTC, Dm94st commented on Wake On Lan/Modules/IAPManager/Sources/IAPManager/Product.swift
> +public struct Product {
1. зачем интиернал?
2. квик хелп

2023-05-01 11:57 UTC, Dm94st commented on Wake On Lan/Modules/IAPManager/Sources/IAPManager/Product.swift
> +    internal let skProduct: SKProduct
зачем он тут?

2023-05-01 11:57 UTC, Dm94st commented on Wake On Lan/Modules/WOLUIComponents/Sources/WOLUIComponents/Elements/View/SpinnerView/SpinnerView.swift
> +public final class SpinnerView: UIView {
тоже запротоколить ее надо бы

2023-05-01 11:57 UTC, Dm94st commented on Wake On Lan/Modules/DonateScreen/Sources/DonateScreen/DonateScreenState.swift
> +enum DonateScreenState {
посмотри тут SteatefulView, я уже делал подобное, должно подойти

2023-05-25 14:53 UTC, tr1ckyf0x commented on Wake On Lan/Modules/DonateScreen/Sources/DonateScreen/DonateScreenState.swift
> +enum DonateScreenState {
Не подходит

2023-05-25 14:55 UTC, tr1ckyf0x commented on Wake On Lan/Modules/DonateScreen/Sources/DonateScreen/DonateScreenFactory.swift
> +import RouteComposer
Не подходит. Там используется RouteComposer.Factory

2023-05-25 14:59 UTC, tr1ckyf0x commented on Wake On Lan/Modules/DonateScreen/Sources/DonateScreen/DonateScreenInteractor.swift
> +        Task {
Нет. `Task` - это как `DispatchQueue.global.async { }` Она держит ссылку пока выполняется, но тут нет цикла

2023-05-25 16:29 UTC, tr1ckyf0x commented on Wake On Lan/Modules/DonateScreen/Sources/DonateScreen/DonateScreenViewController.swift
> +    private lazy var tableManager: ManagesDonateScreenTable = {
Во всем проекте это хранится в VC. Надо либо все менять, либо дальше так делать

2023-05-25 16:29 UTC, tr1ckyf0x commented on Wake On Lan/Modules/DonateScreen/Sources/DonateScreen/DonateScreenViewController.swift
> +        navigationItem.leftBarButtonItem = rootView.backBarButton
То же самое, во всем проекте так

2023-05-25 16:38 UTC, tr1ckyf0x commented on Wake On Lan/Modules/IAPManager/Sources/IAPManager/IAPManager.swift
> +        formatter.locale = product.priceLocale
нет

2023-05-30 18:09 UTC, closed without merging