Implemented host reordering
tr1ckyf0x/wakeonlan-ios pull request #69
Opened 2023-11-21 15:51 UTC by tr1ckyf0x

- DB migration
- Drag&Drop

2023-11-22 12:00 UTC, Dm94st requested changes

2023-11-22 12:00 UTC, Dm94st commented on Modules/HostList/HostList/HostListCellProvider.swift
> +    private weak var hostCellDelegate: HostListTableViewCellDelegate?
делегату не место в провайдере

2023-11-22 12:00 UTC, Dm94st commented on Frameworks/CoreDataService/Models/Host.swift
> +    @NSManaged public internal(set) var id: UUID
а чем деволтный objID не подходит?

2023-11-22 12:00 UTC, Dm94st commented on Frameworks/CoreDataService/Workers/HostCRUDWorker.swift
> +        completion: ((Result<Void, Error>) -> Void)?
тут error там swift.error

2023-11-22 12:00 UTC, Dm94st commented on Frameworks/CoreDataService/Workers/HostCRUDWorker.swift
> +public protocol PerformsHostCRUD {
```swift
public protocol PerformsCRUD<T: NSManagedObject> {
    typealias CompletionHandler = (Result<Void, Error>) -> Void

    func create<T>(
        from form: T,
        in context: NSManagedObjectContext,
        completion: CompletionHandler?
    )

    func update<T>(
        host: T,
        in context: NSManagedObjectContext,
        with form: T,
        completion: CompletionHandler?
    )

    func delete(
        object: T,
        context: NSManagedObjectContext
    )
}
```

2023-11-22 12:00 UTC, Dm94st commented on Frameworks/CoreDataService/Workers/HostCRUDWorker.swift
> +public protocol PerformsHostCRUD {
так не получится? не хочу на сущность завязываться конкретную

2023-11-22 12:00 UTC, Dm94st commented on Frameworks/CoreDataService/Workers/HostCRUDWorker.swift
> +public protocol PerformsHostCRUD {
и не надо кстати сюда мув пихать, это не круд

2023-11-22 12:00 UTC, Dm94st commented on Frameworks/CoreDataService/Workers/HostCRUDWorker.swift
> +                host.order = index
это нужно для сортировки или зачем?

2023-11-22 12:00 UTC, Dm94st commented on Frameworks/CoreDataService/Workers/HostCRUDWorker.swift
> +                    host.order += 1
тоже не понимаю этого

2023-11-22 12:00 UTC, Dm94st commented on Frameworks/CoreDataService/Workers/HostCRUDWorker.swift
> +        let host: Host = context.insertObject()
```suggestion
        let host = context.insertObject()
```

2023-11-22 12:00 UTC, Dm94st commented on Frameworks/CoreDataService/Workers/HostCRUDWorker.swift
> +                completion?(.success(Void()))
а тут что с комплишенов? почему воид?

2023-11-22 12:00 UTC, Dm94st commented on Frameworks/WOLUIComponents/Protocols/ProvidesTableViewCell.swift
> +public protocol ProvidesTableViewCell<ItemIdentifierType> {
погоди, а какое это вообще имеет отношение к дизайн-системе нашей?

2023-11-22 12:00 UTC, Dm94st commented on Frameworks/WOLUIComponents/Protocols/ProvidesTableViewCell.swift
> +public protocol ProvidesTableViewCell<ItemIdentifierType> {
да и потом, не надо директории называть protocols, models и прочими общими словами, это потом превразается в помойку

2023-11-22 12:00 UTC, Dm94st commented on Modules/AddHost/AddHostForm/AddHostInteractor.swift
> +            in: coreDataService.createChildConcurrentContext()
это в переменной лучше было оставить

2023-11-22 12:00 UTC, Dm94st commented on Modules/AddHost/AddHostForm/AddHostInteractor.swift
> +            guard let self else { return }
можно просто чреез ? распаковать если мало упоминаний

2023-11-22 12:00 UTC, Dm94st commented on Modules/HostList/HostList/HostListCacheTracker.swift
> +    func hostAtIndexPath(_ indexPath: IndexPath) -> Host
а вот это уже похоже на круд-операцию `read`

2023-11-22 12:00 UTC, Dm94st commented on Modules/HostList/HostList/HostListCacheTracker.swift
> +    func hostAtIndexPath(_ indexPath: IndexPath) -> Host
```suggestion
    func fetchHost(at indexPath: IndexPath) -> Host
```
давай в свифтовом стиле перепищем

2023-11-22 12:00 UTC, Dm94st commented on Modules/HostList/HostList/HostListCacheTracker.swift
> +    var fetchedObjects: [Host]? { get }
тут точно массив опциональный нужен? имхо - лучше сделать проверку на пустоту

2023-11-22 12:00 UTC, Dm94st commented on Modules/HostList/HostList/HostListCellProvider.swift
> +    private weak var hostCellDelegate: HostListTableViewCellDelegate?
ты можешь сначала сделать ячейку а потом сконфигурить ее

2023-11-22 12:02 UTC, tr1ckyf0x commented on Frameworks/CoreDataService/Models/Host.swift
> +    @NSManaged public internal(set) var id: UUID
кстати уже не нужен. Это в первой реализации drag and drop нужен был

2023-11-25 09:07 UTC, tr1ckyf0x commented on Frameworks/CoreDataService/Workers/HostCRUDWorker.swift
> +                host.order = index
да

2023-11-25 09:08 UTC, tr1ckyf0x commented on Modules/AddHost/AddHostForm/AddHostInteractor.swift
> +            guard let self else { return }
нельзя. self передается в делегате

2023-12-09 14:12 UTC, tr1ckyf0x reviewed
LGTM

2023-12-09 14:53 UTC, merged